version: '3'

services:
  php_fpm:
    container_name: re_app_php
    build: .
    user: www-data
    env_file:
      - .env
    expose:
      - 9000
    ports:
      - "33:20"
    depends_on:
      - database
    volumes:
      - .:/opt/app
      - /var/log/re_app/php:/var/log/app
    networks:
      - re_app_network

  database:
    container_name: re_app_db
    image: postgres:15rc1-alpine
    env_file:
      - .env
    environment:
      - "POSTGRES_DB=${DB_DATABASE}"
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    volumes:
      - /var/data/re_app/postgres/:/var/lib/postgresql/data
    ports:
      - 5544:5432
    networks:
      - re_app_network

  nginx:
    container_name: re_app_nginx
    image: nginx:1.23.1-alpine
    ports:
      - 500:80
    volumes:
      - ./:/opt/app
      - /var/log/re_app/nginx/:/var/log/nginx/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - re_app_network
    depends_on:
      - php_fpm

networks:
  re_app_network:
    driver: bridge
